### PR TITLE
Add `@JvmField` to `TypeName` constants

### PR DESCRIPTION
**Pull request by arouel**
# What

- Add `@JvmField` to `TypeName` constants
- Update Kotlin to 1.7.10
- Update JaCoCo to 0.8.7
- Update Guava to 31.1-jre
- Set release version to 1.1.3

# Why

- Let the Kotlin compiler know that we want to expose constants like `TypeName.NUMBER` as a static field in the Java representation.
- Get the project running with OpenJDK 11.
- Benefit from bug fixes and improvements of a recent Kotlin version.

### CODE REVIEW

**Comment by kdubb** [comment]
These should be separate PRs

**Comment by kdubb** [comment]
And you should _not_ change the release version. That only happens when a release is made.

**Comment by arouel** [comment]
I will create separate PRs. Thank you for the feedback.

**Comment by arouel** [comment]
@kdubb I close this PR in favor of
#17 
#18 
#19 
#20

**Pull request closed without merging**
